# Generated by Django 3.2.21 on 2023-09-22 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_auto_20230919_1117'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('G', 'Graphic'), ('V', 'Video'), ('A', 'Audio'), ('CW', 'Copywriting'), ('O', 'Other')], default='G', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='../default_asset_img_dwjzkq', upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_project', to='projects.project')),
            ],
        ),
    ]
