# Generated by Django 3.2.21 on 2023-09-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20230919_1117'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='project_id',
        ),
        migrations.AddField(
            model_name='asset',
            name='projects',
            field=models.ManyToManyField(to='projects.Project'),
        ),
    ]
