# Generated by Django 3.2.21 on 2023-09-22 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20230919_1117'),
        ('assets', '0002_auto_20230922_0800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='asset',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_project', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('asset_name', 'project_id')},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='projects',
        ),
    ]
