# Generated by Django 3.2.21 on 2023-09-23 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20230919_1117'),
        ('assets', '0003_auto_20230922_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='project_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='asset_project', to='projects.project'),
            preserve_default=False,
        ),
    ]
