# Generated by Django 3.2.21 on 2023-09-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_asset_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('graphic', 'Graphic'), ('video', 'Video'), ('audio', 'Audio'), ('copywriting', 'Copywriting'), ('other', 'Other')], default='G', max_length=32),
        ),
    ]
