# Generated by Django 3.2.21 on 2023-10-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_asset_assetfile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set(),
        ),
    ]
