# Generated by Django 3.2.21 on 2023-10-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_asset_assetfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('graphic', 'graphic'), ('video', 'video'), ('audio', 'audio'), ('copywriting', 'copywriting'), ('other', 'other')], default='other', max_length=32),
        ),
    ]
