# Generated by Django 3.2.21 on 2023-10-25 17:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_asset_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assetfile',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Asset'),
        ),
    ]
