# Generated by Django 3.2.21 on 2023-09-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='asset',
            new_name='asset_id',
        ),
    ]
